// Code generated by "stringer -type=StorageMethod"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Get-0]
	_ = x[Delete-1]
	_ = x[Put-2]
}

const _StorageMethod_name = "GetDeletePut"

var _StorageMethod_index = [...]uint8{0, 3, 9, 12}

func (i StorageMethod) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StorageMethod_index)-1 {
		return "StorageMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StorageMethod_name[_StorageMethod_index[idx]:_StorageMethod_index[idx+1]]
}
