apiVersion: kerrareg.io/v1alpha1
kind: Module
metadata:
  name: terraform-azurerm-aks
  namespace: defdevio
spec:
  moduleConfig:
    fileFormat: zip
    githubClientConfig:
      useAuthenticatedClient: true
    immutable: true
    provider: azurerm
    repoOwner: defdevio
    repoUrl: https://github.com/defdevio/terraform-azurerm-aks
    storageConfig:
      s3:
        bucket: kerrareg-module-store
        region: us-west-2
  versions:
  - version: v0.0.2
  - version: v0.0.1
  - version: v0.0.3
