package types

//go:generate stringer -type=KerraregType
type KerraregType int

const (
	Module KerraregType = iota
	Provider
)

const (
	KerraregFinalizer                       = "kerrareg.io/finalizer"
	KerraregGithubSecretDataFieldAppID      = "githubAppID"
	KerraregGithubSecretDataFieldInstallID  = "githubInstallID"
	KerraregGithubSecretDataFieldPrivateKey = "githubPrivateKey"
	KerraregGithubSecretName                = "kerrareg-github-application-secret"
	KerraregModule                          = "Module"
	KerraregProvider                        = "Provider"
)

// The configuration settings for storing the module in an Amazon S3 bucket.
type AmazonS3Config struct {
	// The S3 bucket name.
	Bucket string `json:"bucket"`
	// The S3 bucket key, ie: 'my/bucket/prefix'
	// The file name will be automatically generated by the kerrareg-module-controller.
	Key *string `json:"key,omitempty"`
	// The AWS region for the bucket.
	Region string `json:"region"`
}

type GithubClientConfig struct {
	// This flag determines whether the GitHub client used to download modules
	// will be authenticated with a Github App. It's highly recommended
	// to enable this flag to avoid GitHub API rate limiting. When enabled, the namespace where the Module resource exists
	// must contain a Secret named 'kerrareg-github-application-secret'. The secret must contain a githubAppID,
	// githubInstallID, and githubPrivateKey field. The private key must also be base64 encoded before being added
	// as data to the secret. When accessed, the controller will base64 decode the key to build an in-memory client
	// to authenticate with the Github API.
	UseAuthenticatedClient bool `json:"useAuthenticatedClient,omitempty"`
}

// ModuleConfig is the configuration settings for the Module and for each
// Version created by the Module controller.
type ModuleConfig struct {
	// The file format of the module
	// This must be one of 'zip' or 'tar'.
	FileFormat string `json:"fileFormat,omitempty"`
	// The Github client configuration settings.
	GithubClientConfig *GithubClientConfig `json:"githubClientConfig,omitempty"`
	// When true, enforces that the ChecksumSHA256 of the module archive
	// always matches the value stored in this field and in any destination storage config.
	Immutable bool `json:"immutable,omitempty"`
	// The name of the module. If omitted, the name of the Module resource
	// is used in its place.
	Name *string `json:"name,omitempty"`
	// The main terraform or tofu provider required for this module.
	Provider string `json:"provider,omitempty"`
	// Owner of the Github repository.
	RepoOwner string `json:"repoOwner,omitempty"`
	// The full URL of the Github repository.
	RepoUrl string `json:"repoUrl,omitempty"`
	// The external storage configuration settings.
	StorageConfig StorageConfig `json:"storageConfig,omitempty"`
	// A comma separated list of version constraints such as
	// '1.2.1' or '>= 1.0.0, < 2.0.0' or '~> 1.0.0, != 1.0.2'. This field is only
	// respected by the Depot controller.
	VersionConstraints string `json:"versionConstraints,omitempty"`
}

// ModuleVersion holds details about the Version resource under management.
type ModuleVersion struct {
	// The randomly generated filename with its file extension.
	FileName string `json:"fileName,omitempty"`
	// The name of the module.
	Name string `json:"name,omitempty"`
	// Whether the Version for the Module has synced or not.
	Synced bool `json:"synced,omitempty"`
	// The version of the module.
	Version string `json:"version,omitempty"`
}

// ProviderConfig is the configuration settings for the Provider and for each
// Version created by the Provider controller.
type ProviderConfig struct {
	// The name of the provider.
	Name *string `json:"name,omitempty"`
}

// StorageConfig holds details about how to store a Version.
type StorageConfig struct {
	// The configuration settings for storing Versions on a local filesystem.
	FileSystem *FileSystemConfig `json:"fileSystem,omitempty"`
	// The configuration settings for storing Versions in an Amazon S3 bucket.
	S3 *AmazonS3Config `json:"s3,omitempty"`
}

// The configuration settings for storing Versions on a local filesystem.
type FileSystemConfig struct {
	// The directory path on the file system where the Version will be stored.
	DirectoryPath *string `json:"directoryPath,omitempty"`
}

// Do not edit the functions below this line
// as they're auto-generated by the operator-sdk
func (in *AmazonS3Config) DeepCopyInto(out *AmazonS3Config) {
	*out = *in
}

func (in *AmazonS3Config) DeepCopy() *AmazonS3Config {
	if in == nil {
		return nil
	}
	out := new(AmazonS3Config)
	in.DeepCopyInto(out)
	return out
}

func (in *FileSystemConfig) DeepCopyInto(out *FileSystemConfig) {
	*out = *in
}

func (in *FileSystemConfig) DeepCopy() *FileSystemConfig {
	if in == nil {
		return nil
	}
	out := new(FileSystemConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ModuleConfig) DeepCopyInto(out *ModuleConfig) {
	*out = *in
	out.GithubClientConfig = in.GithubClientConfig
	in.StorageConfig.DeepCopyInto(&out.StorageConfig)
}

func (in *ModuleConfig) DeepCopy() *ModuleConfig {
	if in == nil {
		return nil
	}
	out := new(ModuleConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(AmazonS3Config)
		**out = **in
	}
	if in.FileSystem != nil {
		in, out := &in.FileSystem, &out.FileSystem
		*out = new(FileSystemConfig)
		**out = **in
	}
}

func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}
