// Code generated by "stringer -type=KerraregType"; DO NOT EDIT.

package v1alpha1

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeModule-0]
	_ = x[TypeProvider-1]
}

const _KerraregType_name = "ModuleProvider"

var _KerraregType_index = [...]uint8{0, 6, 14}

func (i KerraregType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_KerraregType_index)-1 {
		return "KerraregType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KerraregType_name[_KerraregType_index[idx]:_KerraregType_index[idx+1]]
}
